//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillingSystemDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Installment
    {
        public int Id { get; set; }
        public int InstallmentId { get; set; }
        public int InstallmentSequenceNumber { get; set; }
        public System.DateTime InstallmentSendDate { get; set; }
        public System.DateTime InstallmentDueDate { get; set; }
        public double DueAmount { get; set; }
        public Nullable<double> PaidAmount { get; set; }
        public Nullable<double> BalanceAmount { get; set; }
        public string InvoiceStatus { get; set; }
        public int InstallmentSummaryId { get; set; }
        public int InvoiceId { get; set; }
    
        public virtual InstallmentSummary InstallmentSummary { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
